In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [7]:
a=np.array([1,2,3,4,5],ndmin=2)
a

array([[1, 2, 3, 4, 5]])

In [8]:
a=np.array([1,2,3],dtype=complex)
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [9]:
dt=np.dtype(np.int32)
dt

dtype('int32')

In [10]:
a=np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [11]:
a.shape=(3,2)

In [12]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
a=np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
a=np.arange(24)
a.ndim

1

In [16]:
b=a.reshape(2,4,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [18]:
x=np.array([1,2,3,4,5],dtype=np.float32)
x.itemsize

4

In [19]:
x=np.array([1,2,3,4,5])
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [20]:
x=np.empty([3,2],dtype=int)
x

array([[0, 0],
       [0, 0],
       [0, 0]])

In [21]:
x=np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [23]:
x=np.zeros((5,),dtype=np.int)
x

array([0, 0, 0, 0, 0])

In [25]:
x=np.ones(5)
x

array([1., 1., 1., 1., 1.])

In [26]:
x=np.ones([2,2],dtype=int)
x

array([[1, 1],
       [1, 1]])

In [27]:
x=[1,2,3]
a=np.asarray(x)
a

array([1, 2, 3])

In [28]:
x=[1,2,3]
a=np.asarray(x,dtype=float)
a

array([1., 2., 3.])

In [29]:
x=(1,2,3,4,5)
a=np.asarray(x)
a

array([1, 2, 3, 4, 5])

In [30]:
x=[((1,2,3),(4,5,6))]
a=np.asarray(x)
a

array([[[1, 2, 3],
        [4, 5, 6]]])

In [31]:
a.ndim

3

In [39]:
import numpy as np
s= 'Hello World'
a=np.frombuffer(s,dtype='S1')
a

TypeError: a bytes-like object is required, not 'str'

In [41]:
lst=range(5)
lst

range(0, 5)

In [42]:
lst=range(5)
it=iter(lst)
x=np.fromiter(it,dtype=float)
x

array([0., 1., 2., 3., 4.])

In [44]:
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

In [45]:
x=np.arange(5,dtype=float)
x

array([0., 1., 2., 3., 4.])

In [46]:
x=np.arange(10,20,2)
x

array([10, 12, 14, 16, 18])

In [47]:
x=np.linspace(10,20,5)
x

array([10. , 12.5, 15. , 17.5, 20. ])

In [48]:
x=np.linspace(10,20,5,endpoint=False)
x

array([10., 12., 14., 16., 18.])

In [49]:
x=np.linspace(1,2,5,retstep=True)
x

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)

In [50]:
a=np.logspace(1.0,2.0,num=10)
a

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [51]:
a=np.logspace(1,10,num=10,base=2)
a

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [54]:
import numpy as np
a=np.arange(10)
s=slice(2,7,2)
a[s]

array([2, 4, 6])

In [55]:
a=np.arange(10)
s=a[2:7:2]
s



array([2, 4, 6])

In [56]:
a=np.arange(10)
b=a[5]
b

5

In [57]:
a=np.arange(10)
a[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
a=np.arange(10)
a[2:5]

array([2, 3, 4])

In [59]:
#muli-dimensional


In [64]:
a=np.array([[1,2,3],[3,4,5],[4,5,6]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [80]:
a[1:3,1:3]

array([[4, 5],
       [5, 6]])